#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-
# Copyright muflax <mail@muflax.com>, 2013
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

require "trollop"

Commands = [
  "normalize",
  "sort",
  "sort -u | uniq",
].join("\n")

def read_command
  dmenu_opts="-b -i -fn '-mplus-gothic-medium-r*12' -nb '#000000' -nf '#FFFFFF' -sb '#ff8c00' -sf '#000000'"

  command = %x{echo -n '#{Commands}' | dmenu #{dmenu_opts}} || ""

  command.strip
end

def send_key key
  if key.include? "+"
    keys = key.split("+")
    modifiers, key = keys[0..-2], keys[-1]

    cmds = []
    modifiers.each {|mod| cmds << "'keydown #{mod}'"}
    cmds << "'key #{key}'"
    modifiers.each {|mod| cmds << "'keyup #{mod}'"}
    system "xte #{cmds.join(" ")}"
  else
    system "xte 'key #{key}'"
  end
end

opts = Trollop::options do
  opt :paste,    "copy-and-paste mode"
  opt :command,  "explicit command to run", :type => :string
end

command = opts[:command] || read_command

if command.empty?
  puts "you need to specify a command"
  exit 1
end

# make sure the selection gets copied
if opts[:paste]
  # clear clipboard first
  system "echo -n | xclip -i"
  send_key "Control_L+c"
end

# read the selection
selection = %x{xclip -o} || ""
if selection.empty? and opts[:paste]
  puts "no input, aborting..."
  exit 1
end

output = nil
IO.popen(command, "w+") do |cmd|
  cmd << selection
  cmd.close_write

  output = cmd.read
end

# put it into the clipboard (and clear it first so Klipper doesn't interfere)
system "echo -n | xclip -i"
IO.popen("xclip -i", "w+") do |cmd|
  cmd << output
  cmd.close_write
end

# and paste it back in
if opts[:paste]
  send_key "Control_L+v"
end
