#!/bin/zsh
# Copyright muflax <mail@muflax.com>, 2013
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

source ~/.zsh/env.sh
source ~/.zsh/path.sh

BACKUP_DIR="/mnt/nfs/backup"
BACKUP_MACHINE="pleonasty"
DATE_FORMAT="+%Y-%m-%d"

function is_locked() {
  # check for lockfile
  if [[ -f /tmp/rbs.lock ]]; then
    # process already running?
    if [[ "$(ps -p $(cat /tmp/rbs.lock) | wc -l)" -gt 1 ]]; then
      echo "locked"
      return
    fi
  fi
  echo "unlocked"
}

if [[ $(is_locked) == "locked" ]]; then
  echo "process already running, aborting..."
  exit 1
fi

# create lockfile
rm -f /tmp/rbs.lock
echo $$ > /tmp/rbs.lock

echo "update local bup index..."
cd $HOME # do it here so that the bupignore paths work without rewriting
ionice -c3 bup index -u $HOME --xdev --exclude-from $HOME/.bupignore

# check if backup machine is available
ping -w 5 -c 1 $BACKUP_MACHINE
if [ $? -eq 0 ]; then
  # start backup
  
  echo "saving daily pigs..."
  ionice -c3 /bin/mv $HOME/pigs/daily/* $BACKUP_DIR/daily_pigs/
  echo "pigs saved."

  echo "copy bup packs..."
  branch="$(hostname)-$(date $DATE_FORMAT)"
  ionice -3 bup save -n $branch $HOME -r $BACKUP_DIR/home/
}

# remove lockfile
rm -f /tmp/rbs.lock
